### ISSUE TITLE
Explain what CYOA is

### ISSUE THREAD

**Issue by olberger** [felixplesoianu/ramus2#1]
Hi.

Interesting project :-)

It may not be obvious to all what a CYOA game is. I have the impression that "Interactive Fiction" is quite a popular term in the field, although there may be subtle differences.

Please make it more explanatory for the profane.

Best regards,

**Comment by felixplesoianu** [comment]
Thank you for the nice words! As for your objection, people in the community know what CYOA means, while people from outside the community don't know what interactive fiction is, either. Documentation for beginners is, of course, desirable in the long term, but for an alpha version it's simply not a priority.

**Comment by olberger** [comment]
Ack. May I suggest to add a link in the description, to a reference document about CYOA, for those outside your community ?

**Comment by felixplesoianu** [comment]
Fair enough, I can do as much. Thanks for the suggestion!
